---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We set the python interpreter to the ansible runtime venv if
# the delegation is to localhost so that we get access to the
# appropriate python libraries in that venv. If the delegation
# is to another host, we assume that it is accessible by the
# system python instead.
- name: Setup the service
  delegate_to: "{{ octavia_service_setup_host }}"
  vars:
    ansible_python_interpreter: >-
      {{ (octavia_service_setup_host == 'localhost') | ternary(ansible_playbook_python, ansible_python['executable']) }}
  block:
    - name: Add service to the keystone service catalog
      os_keystone_service:
        cloud: default
        state: present
        name: "{{ octavia_service_name }}"
        service_type: "{{ octavia_service_type }}"
        description: "{{ octavia_service_description }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      until: add_service is success
      retries: 5
      delay: 10

    - name: Add service user
      os_user:
        cloud: default
        state: present
        name: "{{ octavia_service_user_name }}"
        password: "{{ octavia_service_password }}"
        domain: default
        default_project: "{{ octavia_service_project_name }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not octavia_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10
      no_log: True

    - name: Add service user to admin role
      os_user_role:
        cloud: default
        state: present
        user: "{{ octavia_service_user_name }}"
        role: "{{ octavia_service_role_name }}"
        project: "{{ octavia_service_project_name }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      when: not octavia_service_in_ldap | bool
      until: add_service is success
      retries: 5
      delay: 10

    - name: Add endpoints to keystone endpoint catalog
      os_keystone_endpoint:
        cloud: default
        state: present
        service: "{{ octavia_service_name }}"
        endpoint_interface: "{{ item.interface }}"
        url: "{{ item.url }}"
        region: "{{ octavia_service_region }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_service
      until: add_service is success
      retries: 5
      delay: 10
      with_items:
        - interface: "public"
          url: "{{ octavia_service_publicuri }}"
        - interface: "internal"
          url: "{{ octavia_service_internaluri }}"
        - interface: "admin"
          url: "{{ octavia_service_adminuri }}"
      when: octavia_v2 | bool

    - name: Create service roles
      os_keystone_role:
        cloud: default
        state: present
        name: "{{ item }}"
        endpoint_type: admin
        verify: "{{ not keystone_service_adminuri_insecure }}"
      register: add_roles
      until: add_roles is success
      retries: 5
      delay: 10
      with_items:
        - load-balancer_observer
        - load-balancer_global_observer
        - load-balancer_member
        - load-balancer_admin
        - load-balancer_quota_admin
